Bot:
  token: '' # Discord bot token
  prefix: '?' # Prefix for commands.
  owners:
     - 256132879770189825 # List of owners, this is required, you can add your account ID.
     - 256132879770189825 # You can add more owners.
